<?php

/**
 * Implements hook_menu().
 */
function cfas_menu() {
  $items = array();

  $items['cfas-album'] = array(
    'page callback' => 'cfas_album_submit',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function cfas_theme($existing, $type, $theme, $path) {
  return array(
    'cfas_slideshow' => array(
      'vars' => array(
        'images' => null
      ),
      'template' => 'templates/cfas-slideshow'
    )
  );
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function cfas_wysiwyg_plugin($editor, $version) {
  $plugins = array();
  if ($editor == 'ckeditor' && version_compare($version, '4.0', '>=')) {
    $plugins['flickrAlbumSlideshow'] = array(
      'path' => drupal_get_path('module', 'cfas') . '/plugins/flickrAlbumSlideshow',
      'buttons' => array(
        'flickrAlbumSlideshow' => t('Flickr album slideshow'),
      ),
      'load' => TRUE,
      'internal' => FALSE,
    );
  }
  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function cfas_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
  }
}

/**
 * Implements hook_filter_info().
 */
function cfas_filter_info() {
  $filters['cfas'] = array(
    'title' => t('Embed Flickr album slideshow'),
    'description' => t('By including a div with a data-flickr-album attribute, this filter will embed the a Flickr album slideshow'),
    'process callback' => 'cfas_filter_process',
    'tips callback'  => 'cfas_filter_tips',
    'cache' => FALSE,
  );

  return $filters;
}

function cfas_filter_process($text, $filter) {
  return preg_replace_callback('/<div.*data-flickr-album="(\d+)">[&nbsp;]*<\/div>/U', 'cfas_filter_process_callback', $text);
}

function cfas_filter_tips($filter, $format, $long = FALSE) {
  return t('Insert a Flickr album slideshow.');
}

function cfas_filter_process_callback($matches) {
  // Flexslider deps
  drupal_add_css(libraries_get_path('flexslider') . '/flexslider.css');
  drupal_add_js(libraries_get_path('flexslider') . '/jquery.flexslider-min.js');
  // CFAS deps
  drupal_add_js(drupal_get_path('module', 'cfas') . '/js/cfas--flexslider.js');
  drupal_add_css(drupal_get_path('module', 'cfas') . '/css/cfas.css');

  return cfas_get_album($matches[1]);
}

function cfas_get_album($album_id) {
  module_load_include('php', 'cfas', 'includes/FlickrAlbum');

  $flickr = new FlickrAlbum($album_id);
  $album = $flickr->getAlbum();

  // If no valid album, fetch using Flickr API and store record
  if (empty($album)) {
    $album = $flickr->fetchAlbum();
  }

  // Either way, we now have an album. Now theme the images.
  return theme('cfas_slideshow',
    array(
      'images' => unserialize($album['images'])
    )
  );
}

/**
 * Accept album id from POST data and return images
 */
function cfas_album_submit() {
  // Grab raw POST data
  $json = file_get_contents('php://input');
  $decoded = json_decode($json, true);
  $output = cfas_get_album($decoded['album_id']);
  print $output;
  drupal_exit();
}

/**
 * Implements hook_element_info_alter().
 */
function cfas_element_info_alter(&$types) {
  $types['text_format']['#pre_render'][] = 'cfas_pre_render_text_format';
}

function cfas_pre_render_text_format($element) {
  // Flexslider deps
  $element['#attached']['js'][] = libraries_get_path('flexslider') . '/jquery.flexslider-min.js';
  // CFAS deps
  $element['#attached']['js'][] = drupal_get_path('module', 'cfas') . '/js/cfas--flexslider.js';
  $element['#attached']['js'][] = drupal_get_path('module', 'cfas') . '/js/cfas--drupal.js';
  $element['#attached']['js'][] = drupal_get_path('module', 'cfas') . '/js/cfas--form-submit.js';

  return $element;
}

/**
 * Implements template_preprocess_page()
 */
function cfas_preprocess_page(&$vars) {
  drupal_add_js(array('cfas' => array(
    'flexsliderCss' => libraries_get_path('flexslider') . '/flexslider.css',
  )), 'setting');
}