<?php

/**
 * Implements hook_wysiwyg_plugin().
 */
function cfas_wysiwyg_plugin($editor, $version) {
  $plugins = array();
  if ($editor == 'ckeditor' && version_compare($version, '4.0', '>=')) {
    $plugins['flickrAlbumSlideshow'] = array(
      'path' => drupal_get_path('module', 'cfas') . '/plugins/flickrAlbumSlideshow',
      'buttons' => array(
        'flickrAlbumSlideshow' => t('Flickr album slideshow'),
      ),
      'load' => TRUE,
      'internal' => FALSE,
    );
  }
  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function cfas_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
  }
}

/**
 * Implements template_preprocess_page().
 */
function cfas_preprocess_page(&$vars) {
  drupal_add_css(drupal_get_path('module', 'cfas') . '/css/cfas.css');
}